export const FETCH_EXCHANGE_RATE_START = "FETCH_EXCHANGE_RATE_START";
export const FETCH_EXCHANGE_RATE_SUCCESS = "FETCH_EXCHANGE_RATE_SUCCESS";
export const FETCH_EXCHANGE_RATE_FAILURE = "FETCH_EXCHANGE_RATE_FAILURE";
export const EXHANGE_RATE_CONVERTION = "EXHANGE_RATE_CONVERTION";
